language: node_js
node_js:
  - "4"
  - "5"
  - "6"
after_success:
  - npm i coveralls mocha-lcov-reporter
  - istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls
